# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJJRXkf1oUTVqK0zQXVRBfQwzQl8Cypn
"""

!pip install pyomo
import pyomo.environ as pyo
from pyomo.opt import SolverManagerFactory

model = pyo.ConcreteModel()

model.x1 = pyo.Var(domain = pyo.NonNegativeIntegers)
x1 = model.x1
model.x2 = pyo.Var(domain = pyo.NonNegativeIntegers)
x2 = model.x2

model.obj = pyo.Objective(expr = 30*x1 + 35*x2 - 2*(x1**2) - 3*(x2**2), sense = pyo.maximize)

model.con1 = pyo.Constraint(expr = x1 + x2 <= 20)
model.con2 = pyo.Constraint(expr = x1**2 + 2*(x2**2) <= 250)

import os
os.environ['NEOS_EMAIL']=''
solver = SolverManagerFactory('neos') #SolverManagerFactory should be imported instead of SolverFactory
result = solver.solve(model,opt='minlp')
print(result)
print('objective function =', model.obj())
print('x1=',x1())
print('x2=',x2())

